ruby/blog_3/config/routes.rb
Rails.application.routes.draw do
  # get 'password_resets/create'

  # get 'password_resets/edit'

  # get 'password_resets/update'

  # get 'user_sessions/new'

  # get 'user_sessions/create'

  # get 'user_sessions/destroy'
get "users/index"
get "users/show/:username" => "users#show"


resources :user_sessions
get 'login' => 'user_sessions#new',as: :login
post 'logout' => 'user_sessions#destroy',as: :logout 
resources :users
resources :posts do
resources :comments,only: [:create,:destroy]
resources :password_resets
end
root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ruby/blog_3/app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
	skip_before_filter :require_login,exept:[:destroy]
  def new
  	@user  = User.new
  end

  def create
  	if @user = login(params[:email],params[:password])
  		redirect_back_or_to(:users,notice: 'Login successful')

  	else
  		flash.now[:alert] = 'Login failed'
  		render action: 'new'
  	end
  end

  def destroy
  	logout
  	redirect_to(:users,notice: 'チンポゥ！')
  end
end

ruby/blog_3/app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

ruby/blog_3/app/views/user_sessions/_forgot_password_form.html.erb
<%= form_tag password_resets_path, :method => :post do %>
  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %> <%= submit_tag "Reset my password!" %>
  </div>
<% end %>

ruby/blog_3/app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path,method: :post do %>
<div class="field">
<%= label_tag :email %>
<%= text_field_tag :email %>
</div>
<div class="field">
<%= label_tag :password %>
<%=text_field_tag :password %>
</div>
<div class="actions">
<%=submit_tag "login" %>
</div>
<% end %>

ruby/blog_3/app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

ruby/blog_3/app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

ruby/blog_3/app/views/user_sessions/new.html.erb
<h1>Login</h1>
<%= render 'form' %>
<%link_to 'Back',user_sessions_path %>
<h1>Forgot Password?</h1>
<%= render 'forgot_password_form' %>