ruby/blog_3/config/routes.rb
Rails.application.routes.draw do
  # get 'password_resets/create'

  # get 'password_resets/edit'

  # get 'password_resets/update'

  # get 'user_sessions/new'

  # get 'user_sessions/create'

  # get 'user_sessions/destroy'
get "users/index"
get "users/show/:username" => "users#show"


resources :user_sessions
get 'login' => 'user_sessions#new',as: :login
post 'logout' => 'user_sessions#destroy',as: :logout 
resources :users
resources :posts do
resources :comments,only: [:create,:destroy]
resources :password_resets
end
root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ruby/blog_3/app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def create
  	@user = User.find_by_email(params[:email])
    @user.deliver_reset_password_instructions! if @user
    redirect_to(root_path, :notice => 'Instructions have been sent to your email.')
  end

  def edit
  	set_token_user_from_params?
  end

  def update
  	 return if !set_token_user_from_params?
 
    @user.password_confirmation = params[:user][:password_confirmation]
 
    if @user.change_password!(params[:user][:password])
      redirect_to(root_path, :notice => 'Password was successfully updated.')
    else
      render :action => "edit"
    end
  end

private

def set_token_user_from_params?
      @token = params[:id]
      @user = User.load_from_reset_password_token(params[:id])
 
      if @user.blank?
        not_authenticated
        return false
      else
        return true
      end
    end

end

ruby/blog_3/app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

ruby/blog_3/app/views/password_resets/create.html.erb
<h1>PasswordResets#create</h1>
<p>Find me in app/views/password_resets/create.html.erb</p>

ruby/blog_3/app/views/password_resets/edit.html.erb
<h1>PasswordResets#edit</h1>
<p>Find me in app/views/password_resets/edit.html.erb</p>

<h1>Choose a new password</h1>
<%= form_for @user, :url => password_reset_path(@token), :html => {:method => :put} do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2 id="toc-prohibited-this-user-from-being-saved"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
 
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="field">
    <%= f.label :email %><br />
    <%= @user.email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/blog_3/app/views/password_resets/update.html.erb
<h1>PasswordResets#update</h1>
<p>Find me in app/views/password_resets/update.html.erb</p>