ruby/third_app/config/routes.rb
Rails.application.routes.draw do
  resources :boards do
  resources :comments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

# root to: 'board#index'
end

ruby/third_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/third_app/app/models/board.rb
class Board < ApplicationRecord
	# has_many :comments,dependent: :destroy

	# validates :title,:presence true,length: {in:4..127}
	# validates :editor,:presence true,length: {in: 1..30}
end

ruby/third_app/app/models/comment.rb
class Comment < ApplicationRecord
	# belongs_to :board

	# validates :board,:presence true
	# validates :name,:presence true
	# validates :content,:presence true,length: {in: 1..1000}
end

ruby/third_app/app/models/create_comment.rb
class CreateComment < ApplicationRecord
end

ruby/third_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ruby/third_app/app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:show, :edit, :update, :destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
  end

  def show
    @comment = Comment.new
  end

  # GET /boards/new
  def new
    @board = Board.new
  end


  # GET /boards/1/edit
  def edit
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_board
      @board = Board.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def board_params
      params.require(:board).permit(:title, :editor)
    end
end

ruby/third_app/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @board = Board.find(params[:board_id])
    @comment = Comment.new(comment_params)
    @comment.board = @board

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:title, :editor)
    end
end

ruby/third_app/app/controllers/create_comments_controller.rb
class CreateCommentsController < ApplicationController
  before_action :set_create_comment, only: [:show, :edit, :update, :destroy]

  # GET /create_comments
  # GET /create_comments.json
  def index
    @create_comments = CreateComment.all
  end

  # GET /create_comments/1
  # GET /create_comments/1.json
  def show
  end

  # GET /create_comments/new
  def new
    @create_comment = CreateComment.new
  end

  # GET /create_comments/1/edit
  def edit
  end

  # POST /create_comments
  # POST /create_comments.json
  def create
    @create_comment = CreateComment.new(create_comment_params)

    respond_to do |format|
      if @create_comment.save
        format.html { redirect_to @create_comment, notice: 'Create comment was successfully created.' }
        format.json { render :show, status: :created, location: @create_comment }
      else
        format.html { render :new }
        format.json { render json: @create_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /create_comments/1
  # PATCH/PUT /create_comments/1.json
  def update
    respond_to do |format|
      if @create_comment.update(create_comment_params)
        format.html { redirect_to @create_comment, notice: 'Create comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @create_comment }
      else
        format.html { render :edit }
        format.json { render json: @create_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /create_comments/1
  # DELETE /create_comments/1.json
  def destroy
    @create_comment.destroy
    respond_to do |format|
      format.html { redirect_to create_comments_url, notice: 'Create comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_create_comment
      @create_comment = CreateComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def create_comment_params
      params.require(:create_comment).permit(:name, :comment)
    end
end

ruby/third_app/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/third_app/app/helpers/boards_helper.rb
module BoardsHelper
end

ruby/third_app/app/helpers/comments_helper.rb
module CommentsHelper
end

ruby/third_app/app/helpers/create_comments_helper.rb
module CreateCommentsHelper
end

ruby/third_app/app/views/boards/_form.html.erb
<div class="wrapper">
<%= form_for(board) do |f| %>
  <% if board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(board.errors.count, "error") %> prohibited this board from being saved:</h2>

      <ul>
      <% board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :editor %>
    <%= f.text_field :editor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>
</div>

ruby/third_app/app/views/boards/edit.html.erb
<div class="wraper">
<h1>編集画面</h1>

<div class="container">
<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', boards_path %>
</div>

ruby/third_app/app/views/boards/index.html.erb
<div class="wrapper wrapper_bg">
<p id="notice"><%= notice %></p>
<div class="wrapper">
<h1>僕はできそこないです</h1>

<div class="menu">
<table>
  <thead>
    <tr>
      <th>題名</th>
      <th>内容</th>
      <th colspan="3"></th>
    </tr>
  </thead>
</div>
<div class="container">
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.title %></td>
        <td><%= board.editor %></td>
        <td><%= link_to 'Show', board %></td>
        <td><%= link_to 'Edit', edit_board_path(board) %></td>
        <td><%= link_to 'Destroy', board, method: :delete, data: { confirm: '本当にいいのかい？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>



<%= link_to 'New Board', new_board_path %>
</div>
</div>

ruby/third_app/app/views/boards/new.html.erb
<h1>投稿画面</h1>

<p>記事投稿<%= render 'form', board: @board %></p>

<%= link_to 'Back', boards_path %>
 

ruby/third_app/app/views/boards/show.html.erb
<div class="wrapper">
<p id="notice"><%= notice %></p>

<p>
  <div class="title"> <strong>題名:</strong>
  <%= @board.title %></div>
</p>

<p>
  <strong>内容:</strong>
  <%= @board.editor %>
</p>

<%= link_to 'Edit', edit_board_path(@board) %> |
<%= link_to 'Back', boards_path %>



</div>

ruby/third_app/app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :editor %>
    <%= f.text_field :editor %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/third_app/app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

ruby/third_app/app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Editor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.title %></td>
        <td><%= comment.editor %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

ruby/third_app/app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

ruby/third_app/app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @comment.title %>
</p>

<p>
  <strong>Editor:</strong>
  <%= @comment.editor %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>